"""add new table 'tariff_prices'

Revision ID: 0afefdc323f1
Revises: 6b847c1e070c
Create Date: 2026-09-14 00:45:26.242632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0afefdc323f1'
down_revision: Union[str, Sequence[str], None] = '6b847c1e070c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('old_price', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tariffs', sa.Column('is_promo', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('tariffs', 'traffic_limit',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_column('tariffs', 'promo_tariff')
    op.drop_column('tariffs', 'price')
    op.drop_column('tariffs', 'period_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariffs', sa.Column('period_days', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=False))
    op.add_column('tariffs', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tariffs', sa.Column('promo_tariff', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.alter_column('tariffs', 'traffic_limit',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('tariffs', 'is_promo')
    op.drop_table('tariff_prices')
    # ### end Alembic commands ###
