"""empty message

Revision ID: 1209b100dc43
Revises: a13fd5485a77
Create Date: 2026-07-28 04:06:01.015797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1209b100dc43'
down_revision: Union[str, Sequence[str], None] = 'a13fd5485a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('provider', sa.Enum('YOOKASSA', 'BALANCE', name='paymentprovider', native_enum=False), nullable=False))
    op.add_column('invoices', sa.Column('duration_days', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'duration_days')
    op.drop_column('invoices', 'provider')
    # ### end Alembic commands ###
