"""set default value balance = 0.0 and nullbale=False

Revision ID: 1335b1301f12
Revises: 5030d04818f2
Create Date: 2026-07-17 13:50:41.985218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1335b1301f12'
down_revision: Union[str, Sequence[str], None] = '5030d04818f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "balance", nullable=False, server_default='0.0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "balance", nullable=True, server_default=None)
    # ### end Alembic commands ###
