"""feat: add referrer_id in users table

Revision ID: 1569e463a78d
Revises: 08932855afc1
Create Date: 2026-09-23 23:53:00.300685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1569e463a78d'
down_revision: Union[str, Sequence[str], None] = '08932855afc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['referrer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referrer_id')
    # ### end Alembic commands ###
