"""empty message

Revision ID: 1d8c49ac6ae5
Revises: 1209b100dc43
Create Date: 2026-07-31 03:59:43.922746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d8c49ac6ae5'
down_revision: Union[str, Sequence[str], None] = '1209b100dc43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('operation', sa.String(length=10), server_default='buy', nullable=False))
    op.alter_column('invoices', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('invoices', 'tariff_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PAID', 'CANCELLED', name='paymentstatus'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_constraint(op.f('invoices_user_id_fkey'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('invoices_tariff_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'invoices', 'subscriptions', ['subscription_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'invoices', 'tariffs', ['tariff_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_tariff_id_fkey'), 'invoices', 'tariffs', ['tariff_id'], ['id'])
    op.create_foreign_key(op.f('invoices_user_id_fkey'), 'invoices', 'users', ['user_id'], ['id'])
    op.alter_column('invoices', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('PENDING', 'PAID', 'CANCELLED', name='paymentstatus'),
               existing_nullable=False)
    op.alter_column('invoices', 'tariff_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoices', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('invoices', 'operation')
    op.drop_column('invoices', 'subscription_id')
    # ### end Alembic commands ###
