"""empty message

Revision ID: 47b8a359e6cd
Revises: 7d1edffef77e
Create Date: 2026-08-04 03:22:19.696932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b8a359e6cd'
down_revision: Union[str, Sequence[str], None] = '7d1edffef77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('remnawave_user_id', sa.BigInteger(), nullable=False))
    op.drop_constraint(op.f('subscriptions_sub_uuid_key'), 'subscriptions', type_='unique')
    op.create_unique_constraint(None, 'subscriptions', ['remnawave_user_id'])
    op.drop_column('subscriptions', 'sub_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('sub_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.create_unique_constraint(op.f('subscriptions_sub_uuid_key'), 'subscriptions', ['sub_uuid'], postgresql_nulls_not_distinct=False)
    op.drop_column('subscriptions', 'remnawave_user_id')
    # ### end Alembic commands ###
