"""chane column not none

Revision ID: 54663b08e3a2
Revises: d14bf3cf5e4e
Create Date: 2026-09-25 03:59:33.431819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54663b08e3a2'
down_revision: Union[str, Sequence[str], None] = 'd14bf3cf5e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoices', 'tariff_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.drop_constraint(op.f('invoices_user_id_fkey'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('invoices_tariff_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invoices', 'tariffs', ['tariff_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_users_referrer_id'), 'users', ['referrer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_referrer_id'), table_name='users')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_tariff_id_fkey'), 'invoices', 'tariffs', ['tariff_id'], ['id'])
    op.create_foreign_key(op.f('invoices_user_id_fkey'), 'invoices', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('invoices', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('invoices', 'tariff_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('invoices', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
