"""add new column in subscriptions, started_at and expired_at

Revision ID: 61ca59e7b52f
Revises: f233e99e6ec5
Create Date: 2026-07-20 18:44:45.895124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ca59e7b52f'
down_revision: Union[str, Sequence[str], None] = 'f233e99e6ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False))
    op.add_column('subscriptions', sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tariffs', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'tariffs', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tariffs', type_='unique')
    op.alter_column('tariffs', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('subscriptions', 'expired_at')
    op.drop_column('subscriptions', 'started_at')
    # ### end Alembic commands ###
