"""empty message

Revision ID: 6b1975703fd1
Revises: 1d8c49ac6ae5
Create Date: 2026-08-01 08:21:57.050506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1975703fd1'
down_revision: Union[str, Sequence[str], None] = '1d8c49ac6ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invoices_tariff_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'tariffs', ['tariff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_tariff_id_fkey'), 'invoices', 'tariffs', ['tariff_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
