"""feat: add bool value 'promo_tariff'  in tariffs table

Revision ID: 6b847c1e070c
Revises: eb3237c1316e
Create Date: 2026-09-09 15:36:39.029268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b847c1e070c'
down_revision: Union[str, Sequence[str], None] = 'eb3237c1316e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariffs', sa.Column('promo_tariff', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariffs', 'promo_tariff')
    # ### end Alembic commands ###
