"""feat: update table 'tariff_options'

Revision ID: 759b8ca89bdd
Revises: 0afefdc323f1
Create Date: 2026-09-14 12:04:58.901160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759b8ca89bdd'
down_revision: Union[str, Sequence[str], None] = '0afefdc323f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('old_price', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tariff_prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_prices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tariff_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('old_price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], name=op.f('tariff_prices_tariff_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tariff_prices_pkey'))
    )
    op.drop_table('tariff_options')
    # ### end Alembic commands ###
