"""empty message

Revision ID: 7af904be5e42
Revises: af89168b6aa5
Create Date: 2026-08-04 22:03:12.729808

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7af904be5e42"
down_revision: str | Sequence[str] | None = "af89168b6aa5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # tariffs — таблица пустая, каст не нужен, просто пересоздаём колонку
    op.add_column(
        "tariffs",
        sa.Column(
            "squad_uuids",
            postgresql.ARRAY(postgresql.UUID(as_uuid=True)),
            nullable=False,
        ),
    )

    op.drop_column("subscriptions", "squad_uuids")
    op.add_column(
        "subscriptions",
        sa.Column(
            "squad_uuids",
            postgresql.ARRAY(postgresql.UUID(as_uuid=True)),
            nullable=False,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscriptions",
        "squad_uuids",
        existing_type=sa.ARRAY(sa.UUID()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
