"""add all tables

Revision ID: 7d1edffef77e
Revises: 
Create Date: 2026-08-03 00:44:47.676588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1edffef77e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'provider',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.add_column('tariffs', sa.Column('category', sa.String(length=20), nullable=False))
    op.add_column('tariffs', sa.Column('traffic_limit', sa.BigInteger(), nullable=False))
    op.drop_column('tariffs', 'slug')
    op.drop_constraint(op.f('users_telegram_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_unique_constraint(op.f('users_telegram_id_key'), 'users', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.add_column('tariffs', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tariffs', 'traffic_limit')
    op.drop_column('tariffs', 'category')
    op.alter_column('invoices', 'provider',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
