"""add new table 'tariffs'

Revision ID: 8545c16a3507
Revises: 1c333cef0992
Create Date: 2026-07-18 22:40:36.263426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8545c16a3507'
down_revision: Union[str, Sequence[str], None] = '1c333cef0992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subscriptions', sa.Column('tariff_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subscriptions', 'tariffs', ['tariff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'tariff_id')
    op.drop_table('tariffs')
    # ### end Alembic commands ###
