"""add device_limit

Revision ID: 927a72f961df
Revises: d49e1d1fe998
Create Date: 2026-09-03 18:28:49.541066

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "927a72f961df"
down_revision: str | Sequence[str] | None = "d49e1d1fe998"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("tariffs", sa.Column("device_limit", sa.Integer(), nullable=True))

    # 2. Заполняем существующие записи дефолтным значением (например, 1)
    op.execute("UPDATE tariffs SET device_limit = 1 WHERE device_limit IS NULL")

    # 3. Делаем колонку NOT NULL
    op.alter_column(
        "tariffs", "device_limit", existing_type=sa.Integer(), nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tariffs", "device_limit")
    # ### end Alembic commands ###
