"""feat: change one-to-one relation user-subscription, add column is_test_used

Revision ID: 9813c975a031
Revises: 759b8ca89bdd
Create Date: 2026-09-20 01:15:47.315765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9813c975a031'
down_revision: Union[str, Sequence[str], None] = '759b8ca89bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'subscriptions', ['user_id'])
    op.add_column('users', sa.Column('is_test_used', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_test_used')
    op.drop_constraint(None, 'subscriptions', type_='unique')
    # ### end Alembic commands ###
