"""add column sub_uuid in subscriptions

Revision ID: a13fd5485a77
Revises: dfa4affc410a
Create Date: 2026-07-25 18:46:35.337929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a13fd5485a77'
down_revision: Union[str, Sequence[str], None] = 'dfa4affc410a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('sub_uuid', sa.UUID(), nullable=False))
    op.alter_column('subscriptions', 'expired_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_unique_constraint(None, 'subscriptions', ['sub_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.alter_column('subscriptions', 'expired_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('subscriptions', 'sub_uuid')
    # ### end Alembic commands ###
