"""feat: add external_squad_uuids

Revision ID: a1493483fefc
Revises: 9813c975a031
Create Date: 2026-09-20 02:46:27.423607

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a1493483fefc"
down_revision: str | Sequence[str] | None = "9813c975a031"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "tariffs",
        sa.Column(
            "internal_squad_uuids",
            sa.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'"),
            nullable=True,
        ),
    )
    op.add_column(
        "tariffs",
        sa.Column(
            "external_squad_uuids",
            sa.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'"),
            nullable=True,
        ),
    )

    op.execute(
        "UPDATE tariffs SET internal_squad_uuids = '{}' WHERE internal_squad_uuids IS NULL"
    )
    op.execute(
        "UPDATE tariffs SET external_squad_uuids = '{}' WHERE external_squad_uuids IS NULL"
    )

    op.alter_column("tariffs", "internal_squad_uuids", nullable=False)
    op.alter_column("tariffs", "external_squad_uuids", nullable=False)

    op.alter_column("tariffs", "internal_squad_uuids", server_default=None)
    op.alter_column("tariffs", "external_squad_uuids", server_default=None)

    op.drop_column("tariffs", "squad_uuids")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tariffs",
        sa.Column(
            "squad_uuids",
            postgresql.ARRAY(sa.UUID()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("tariffs", "external_squad_uuids")
    op.drop_column("tariffs", "internal_squad_uuids")
    # ### end Alembic commands ###
