"""empty message

Revision ID: af89168b6aa5
Revises: 47b8a359e6cd
Create Date: 2026-08-04 03:49:03.961712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af89168b6aa5'
down_revision: Union[str, Sequence[str], None] = '47b8a359e6cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('tariff_category', sa.String(length=20), nullable=False))
    op.add_column('subscriptions', sa.Column('squad_uuids', sa.JSON(), nullable=False))
    op.add_column('subscriptions', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.drop_column('subscriptions', 'is_active')
    op.add_column('tariffs', sa.Column('squad_uuids', sa.ARRAY(sa.UUID()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariffs', 'squad_uuids')
    op.add_column('subscriptions', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('subscriptions', 'status')
    op.drop_column('subscriptions', 'squad_uuids')
    op.drop_column('subscriptions', 'tariff_category')
    # ### end Alembic commands ###
