"""feat: add column daily rate

Revision ID: de4476ac0308
Revises: a1493483fefc
Create Date: 2026-09-20 23:56:45.382389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de4476ac0308'
down_revision: Union[str, Sequence[str], None] = 'a1493483fefc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('converted_days', sa.Integer(), server_default='0', nullable=False))
    op.add_column('subscriptions', sa.Column('daily_rate', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False))
    op.drop_column('subscriptions', 'squad_uuids')
    op.add_column('tariffs', sa.Column('external_squad_uuid', sa.ARRAY(sa.UUID()), nullable=True))
    op.drop_column('tariffs', 'external_squad_uuids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariffs', sa.Column('external_squad_uuids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=False))
    op.drop_column('tariffs', 'external_squad_uuid')
    op.add_column('subscriptions', sa.Column('squad_uuids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=False))
    op.drop_column('subscriptions', 'daily_rate')
    op.drop_column('invoices', 'converted_days')
    # ### end Alembic commands ###
