"""feat: add columt telegram_id in subscription_notifications

Revision ID: e83f7651e1ae
Revises: 49929b489edf
Create Date: 2026-10-03 00:45:13.645511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83f7651e1ae'
down_revision: Union[str, Sequence[str], None] = '49929b489edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_notifications', sa.Column('telegram_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'subscription_notifications', 'users', ['telegram_id'], ['telegram_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription_notifications', type_='foreignkey')
    op.drop_column('subscription_notifications', 'telegram_id')
    # ### end Alembic commands ###
