"""feat: add column period_days in tariffs table

Revision ID: eb3237c1316e
Revises: 2be3d086cd65
Create Date: 2026-09-09 15:31:16.868748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb3237c1316e'
down_revision: Union[str, Sequence[str], None] = '2be3d086cd65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariffs', sa.Column('period_days', sa.Integer(), server_default='30', nullable=False))
    op.alter_column('tariffs', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tariffs', 'price',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('tariffs', 'period_days')
    # ### end Alembic commands ###
