"""add column slug in tariff table

Revision ID: f233e99e6ec5
Revises: 8545c16a3507
Create Date: 2026-07-19 00:02:23.848881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f233e99e6ec5'
down_revision: Union[str, Sequence[str], None] = '8545c16a3507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariffs', sa.Column('slug', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariffs', 'slug')
    # ### end Alembic commands ###
